### ISSUE TITLE
packaging for egi/pynetstation

### ISSUE THREAD

**Issue by peircej** [gaelen/python-egi#1]
Hi there, 

**Background:** I'm the creator of psychopy and I've typically included egi/pynetstation in that. I was also concerned that it would be lost with the close of googlecode hosting so I ported it to github with the (unfulfilled) intention of releasing on pypi to make our lives easier. I've only just discovered that you did the same, and it looks like you went further. 

**Aim:** let's finish the job! ;-) As you've made a few more commits I suggest we work from your port and I'll start linking to this from the psychopy documentation, which will hopefully mean that your github repo will become the top google hit for pynetstation. 

Would you mind if I pushed a release up to pypi on your behalf? I've just successfully built wheels and eggs for both py2.7 and py3 with only a very minor change to the setup.py. I can obviously make you owner of the pypi package if you let me know your username there and then you can downgrade me (e.g. to maintainer?) so we can both push subsequent fixes if needed.

**Comment by peircej** [comment]
I went ahead and uploaded release files:
 https://pypi.python.org/pypi/egi/0.9.0

but I'll take them down if that's not cool :-)
Let me know your pypi username to add you there

**Comment by peircej** [comment]
To complicate things further I've just discovered that the original author of pynetstation @nm13 has also ported across to github here:
  https://github.com/nm13/pynetstation

It would be good to combine under one location (@gaelen's fork?) but with acknowledgement of @nm13 as the original author.

People on the PsychoPy forum are still requesting this tool so it is still useful for the community e.g.:
  http://discourse.psychopy.org/t/import-egi-no-longer-working/1044

**Comment by gaelen** [comment]
Hi @peircej. Everything you say is alright by me.  I haven't had a need to use PsychoPy or Netstation in the last couple years, however I will be using PsychoPy in the next couple months.  I'm active daily on Github but obviously haven't given this repo any love outside of my original needs.

**Comment by peircej** [comment]
OK cool. I've pushed a change to the setup.py acknowledging @nm13 and I've linked this copy and the pypi release page from the psychopy docs http://www.psychopy.org/api/hardware/egi.html

Hopefully this will create a single target location and reduce confsion
